kind: pipeline
type: docker
name: playwright

steps:
  - name: test-e2e
    image: mcr.microsoft.com/playwright:v1.44.0-jammy
    commands:
      - npm install
      - npx playwright install --with-deps
      - npx playwright test
